-- Add Missing Columns and Tables for Cohort HR Features
-- Run this in Supabase SQL Editor

-- 1. Add missing columns to PROFILES
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS department uuid, -- Will reference departments table
ADD COLUMN IF NOT EXISTS job_title text,
ADD COLUMN IF NOT EXISTS employment_type text default 'Full-Time',
ADD COLUMN IF NOT EXISTS join_date date,
ADD COLUMN IF NOT EXISTS team_id bigint; -- For team assignment

-- 2. Create DEPARTMENTS table
CREATE TABLE IF NOT EXISTS public.departments (
  id uuid default gen_random_uuid() primary key,
  department_name text not null,
  org_id uuid,
  created_at timestamptz default now()
);
-- Add RLS
ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Read departments" ON public.departments FOR SELECT USING (true);
CREATE POLICY "Write departments" ON public.departments FOR ALL USING (true);

-- 3. Create ANNOUNCEMENTS table
CREATE TABLE IF NOT EXISTS public.announcements (
  id uuid default gen_random_uuid() primary key,
  title text,
  author_id uuid references public.profiles(id),
  location text, -- 'Broadcast', etc.
  message text,
  description text,
  org_id uuid,
  created_at timestamptz default now()
);
-- Add RLS
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Read announcements" ON public.announcements FOR SELECT USING (true);
CREATE POLICY "Write announcements" ON public.announcements FOR ALL USING (true);

-- 4. Create LEAVES table
CREATE TABLE IF NOT EXISTS public.leaves (
  id bigint generated by default as identity primary key,
  employee_id uuid references public.profiles(id),
  leave_type text,
  from_date date,
  to_date date,
  reason text,
  status text default 'pending', -- 'approved', 'rejected', 'pending'
  org_id uuid,
  created_at timestamptz default now()
);
-- Add RLS
ALTER TABLE public.leaves ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Read leaves" ON public.leaves FOR SELECT USING (true);
CREATE POLICY "Write leaves" ON public.leaves FOR ALL USING (true);

-- 5. Create ATTENDANCE table
CREATE TABLE IF NOT EXISTS public.attendance (
  id bigint generated by default as identity primary key,
  employee_id uuid references public.profiles(id),
  clock_in time,
  clock_out time,
  date date default current_date,
  current_task text,
  org_id uuid,
  created_at timestamptz default now()
);
-- Add RLS
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Read attendance" ON public.attendance FOR SELECT USING (true);
CREATE POLICY "Write attendance" ON public.attendance FOR ALL USING (true);

-- 6. Create POLICIES table
CREATE TABLE IF NOT EXISTS public.policies (
  id uuid default gen_random_uuid() primary key,
  title text,
  category text,
  status text default 'Active',
  effective_date date,
  file_url text, -- Supabase Storage URL
  org_id uuid,
  created_at timestamptz default now()
);
-- Add RLS
ALTER TABLE public.policies ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Read policies" ON public.policies FOR SELECT USING (true);
CREATE POLICY "Write policies" ON public.policies FOR ALL USING (true);

-- 7. Create TEAMS table
CREATE TABLE IF NOT EXISTS public.teams (
  id bigint generated by default as identity primary key,
  team_name text,
  org_id uuid,
  created_at timestamptz default now()
);
-- Add RLS
ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Read teams" ON public.teams FOR SELECT USING (true);
CREATE POLICY "Write teams" ON public.teams FOR ALL USING (true);

-- 8. Create EMPLOYEE_FINANCE table (Salary info)
CREATE TABLE IF NOT EXISTS public.employee_finance (
  id bigint generated by default as identity primary key,
  employee_id uuid references public.profiles(id),
  basic_salary numeric,
  hra numeric,
  allowances numeric,
  is_active boolean default true,
  org_id uuid,
  created_at timestamptz default now()
);
-- Add RLS
ALTER TABLE public.employee_finance ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Read finance" ON public.employee_finance FOR SELECT USING (true);
CREATE POLICY "Write finance" ON public.employee_finance FOR ALL USING (true);

-- 9. Seed some Initial Data
INSERT INTO public.departments (department_name, org_id)
VALUES ('Engineering', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11'),
       ('Design', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11'),
       ('Marketing', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11');

INSERT INTO public.announcements (title, location, message, org_id)
VALUES ('Welcome to Cohort', 'Broadcast', 'Welcome to the new platform!', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11');
